platform :ios, '13.6'

target 'ImgurAPIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 5.4.1'
	pod 'AlamofireImage', '~> 4.1.0'
end
